### ISSUE TITLE
Type cast parameters

### ISSUE THREAD

**Issue by dan-klasson** [Lusito/react-router-ts#5]
I want to be able to typecast the params directly in the Route. Something like

    <Route path="/news/:id">{(params: { id: int }) => <News params={params] />}</Route>

Then access it like

    export const News = (props: RouteComponentProps<{ id: int }>) => (
      <div>News ID: {props.params.id}</div>
    );

If I'm not mistaken, it does not support this right? If so, would it be possible to do this in a `routeMatcherFactory`?

**Comment by Lusito** [comment]
This requires more than just a type-cast, since the routeMatcherFactory always returns a string value. You'd need to be able to specify a type converter per path-expression.

react-router and path-to-regexp don't support this either as far as I can see. There was a [discussion](https://github.com/pillarjs/path-to-regexp/issues/67) about it on the path-to-regexp project, resulting in the statement, that it's out of scope for the project. And I tend to say the same for react-router-ts.

If you have an idea for an implementation, which doesn't add too much bloat and still allows the simple syntax, feel free to explain it. Otherwise I'd say it's not going to be done within this project.

For simple usecases like your sample, you might be able to create a [higher order component](https://reactjs.org/docs/higher-order-components.html), which does the conversion and typing for you. I'm thinking some usage like this:

```typescript
export const News = typedRouteParamsComponent({ id: parseInt }, (props) => (
  <div>News ID: {props.params.id}</div>
))
```

The types of props.params would then be inferred by looking at the return types of the functions specified in the `{ id: parseInt }` map. I.e. ReturnType<typeof parseInt> = number, so props.params would be inferred as type `{ id: number }`
